//tinfo200:[2021-03-10-<aram2020>-dykstra1]- the ICollection allows the enrollments property to be used as a list. you can have many course entities under the same enrollment entities, like
//if you wanted to take the same class multiple times.we also have a course ID which will not be generated by the database, it will be generated by the user.


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }


    }
}
